name: Python Tests  # tiger section 
on: 
    push:
        branches:
        - main,develop
    pull_request:
        branches:
        - main

jobs:    #  job definition
  test:   # job name 
    runs-on: ubuntu-latest # os to run on 

    steps:
    - name: Checkout code   # get your code
      uses: actions/checkout@v4  # uses a prebuilt action

    - name: Set up Python   # install python 
      uses: actions/setup-python@v4 
      with:
        python-version: '3.9'
    
    - name: Install dependencies # install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests with pytest # run tests
      run: |
        python -m pytest tests/ -v
        continue-on-error: false
          